version: "3.3"
services:
  resonite:
    image: leocatsune/resonite-headless-dotnet:latest
    container_name: resonite-headless
    tty: true
    stdin_open: true
    environment:
      STEAMBETA: headless
      STEAMBETAPASSWORD: CHANGEME
      STEAMLOGIN: "USER PASSWORD"
      ENABLE_MODLOADER: false
    volumes:
      - "./Config:/Config:ro"
      - "./Logs:/Logs"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
